backend:
  name: test-repo

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - label: 'Metadata'
    name: 'metadata'
    files:
      - label: 'Social Media'
        name: 'media'
        file: 'meta/media.yml'
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'string'
          - label: 'Link'
            name: 'link'
            widget: 'string'
      - label: 'Navigation'
        name: 'nav'
        file: 'meta/nav.yml'
        fields:
          - label: 'Label'
            name: 'label'
            widget: 'string'
          - label: 'Link'
            name: 'link'
            widget: 'string'
          - label: 'External?'
            name: 'external'
            widget: 'boolean'
      - label: 'Links'
        name: 'links'
        file: 'meta/links.yml'
        fields:
          - label: 'Privacy Policy'
            name: 'privacy'
            widget: 'string'
          - label: 'Code of Conduct'
            name: 'coc'
            widget: 'string'
          - label: 'Hacker Apps'
            name: 'hacker'
            widget: 'String'
  - label: 'Sections'
    name: 'sections'
    files:
      - label: 'Splash'
        name: 'splash'
        file: 'sections/splash.yml'
        fields:
          - label: 'Sponsor'
            name: 'sponsor'
            widget: 'image'
            allow_multiple: false
          - label: 'Description'
            name: 'description'
            widget: 'text'
          - label: 'Event Start'
            name: 'start'
            widget: 'date'
          - label: 'Event End'
            name: 'end'
            widget: 'date'
          - label: 'Application End'
            name: 'app_end'
            widget: 'datetime'
          - label: 'Application Link'
            name: 'link'
            widget: 'string'
      - label: 'About'
        name: 'about'
        file: 'sections/about.yml'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'text'
          - label: 'Video'
            name: 'video'
            widget: 'text'
          - label: 'Stats'
            name: 'stats'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'text'
              - label: 'Assets'
                name: 'assets'
                widget: 'image'
      - label: 'Info'
        name: 'info'
        file: 'sections/info.yml'
        fields:
          - label: 'Sections'
            name: 'section'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'text'
              - label: 'Asset'
                name: 'asset'
                widget: 'image'
                allow_multiple: false
      - label: 'Prizes'
        name: 'prizes'
        file: 'section/prizes.yml'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'text'
          - label: 'Assets'
            name: 'assets'
            widget: 'image'
      - label: 'Sponsors'
        name: 'sponsors'
        file: 'section/sponsors.yml'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'text'
          - label: 'Sponsor package'
            name: 'package'
            widget: 'file'
          - label: 'Sponsors'
            name: 'sponsors'
            widget: 'list'
            fields:
              - label: 'Gold Sponsors'
                name: 'gold'
                widget: 'object'
                fields:
                  - label: 'Width of logos'
                    name: 'size'
                    widget: 'string'
                  - label: 'Logos'
                    name: 'logos'
                    widget: 'image'
      - label: 'FAQ'
        name: 'faq'
        file: 'section/faq.yml'
        fields:
          - label: 'Sections'
            name: 'sections'
            widget: 'list'
            fields:
              - label: 'Question'
                name: 'title'
                widget: 'string'
              - label: 'Answer'
                name: 'description'
                widget: 'text'


      
