name: Build container

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master ]
  repository_dispatch:
    types: [ contentful ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup environment
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ secrets.DEPLOYMENT_SUBDOMAIN }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Do testing
      - name: Build testing container
        uses: docker/build-push-action@v2
        with:
          tags: hackthe6ix/${{ secrets.DOCKERHUB_PREVIEW_REPOSITORY }}:testing
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          cache-from: type=local,src=/tmp/.buildx-cache
          target: testing
          push: false
          load: true

      - name: Run tests
        run: /usr/bin/docker run -v ${{ github.workspace }}/static:/usr/var/app/static -v ${{ github.workspace }}/src:/usr/var/app/src hackthe6ix/${{ secrets.DOCKERHUB_PREVIEW_REPOSITORY }}:testing;

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: hackthe6ix/${{ secrets.DOCKERHUB_PREVIEW_REPOSITORY }}:${{ secrets.DEPLOYMENT_SUBDOMAIN }}
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          cache-from: type=local,src=/tmp/.buildx-cache
          target: deploy
          push: true


      # Clean up cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Trigger preview creation
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflow_file_name: create-preview.yml
          inputs: '{ "tag": "${{ secrets.DEPLOYMENT_SUBDOMAIN }}" }'
          repo: hackthe6ix-landing-2020
          owner: hack-the-6ix

      # Print preview link
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Preview link:** [https://${{ secrets.DEPLOYMENT_SUBDOMAIN }}.hackthe6ix.com](https://${{ secrets.DEPLOYMENT_SUBDOMAIN }}.hackthe6ix.com)
          allow-repeats: true
          repo-token: ${{ github.token }}

